export const MOCK_USER = {
  name: "Aria",
  handle: "@aria.chen",
  moodKeywords: ["Powerful", "Effortless", "Sharp"],
  palette: ["#1C1C1C", "#C9A84C", "#8B8682", "#F5EDD6", "#2A2218"],
  favoritesBrand: "The Row",
};

export const MOCK_WARDROBE_ITEMS = [
  {
    id: "1",
    name: "Black Cashmere Coat",
    category: "Outerwear",
    color: "#1C1C1C",
    colorName: "Onyx",
    fabric: "Cashmere",
    timesWorn: 12,
    lastWorn: "2 days ago",
    occasions: ["office", "events"],
    dustOff: false,
    image: null,
  },
  {
    id: "2",
    name: "White Silk Blouse",
    category: "Tops",
    color: "#F5EDD6",
    colorName: "Ivory",
    fabric: "Silk",
    timesWorn: 8,
    lastWorn: "5 days ago",
    occasions: ["office", "events"],
    dustOff: false,
    image: null,
  },
  {
    id: "3",
    name: "Tailored Wool Trousers",
    category: "Bottoms",
    color: "#4A3728",
    colorName: "Walnut",
    fabric: "Wool",
    timesWorn: 6,
    lastWorn: "1 week ago",
    occasions: ["office"],
    dustOff: true,
    image: null,
  },
  {
    id: "4",
    name: "Linen Wide-Leg Pants",
    category: "Bottoms",
    color: "#C8BCA8",
    colorName: "Sand",
    fabric: "Linen",
    timesWorn: 3,
    lastWorn: "3 weeks ago",
    occasions: ["casual"],
    dustOff: true,
    image: null,
  },
  {
    id: "5",
    name: "Leather Oxford Shoes",
    category: "Shoes",
    color: "#3B2A1A",
    colorName: "Cognac",
    fabric: "Leather",
    timesWorn: 15,
    lastWorn: "Yesterday",
    occasions: ["office", "events"],
    dustOff: false,
    image: null,
  },
  {
    id: "6",
    name: "Merino Turtleneck",
    category: "Tops",
    color: "#8B8682",
    colorName: "Greige",
    fabric: "Merino Wool",
    timesWorn: 2,
    lastWorn: "2 weeks ago",
    occasions: ["casual", "office"],
    dustOff: true,
    image: null,
  },
  {
    id: "7",
    name: "Silk Scarf",
    category: "Accessories",
    color: "#C9A84C",
    colorName: "Amber",
    fabric: "Silk",
    timesWorn: 4,
    lastWorn: "4 days ago",
    occasions: ["events"],
    dustOff: false,
    image: null,
  },
  {
    id: "8",
    name: "Black Leather Belt",
    category: "Accessories",
    color: "#1C1C1C",
    colorName: "Black",
    fabric: "Leather",
    timesWorn: 20,
    lastWorn: "Yesterday",
    occasions: ["office", "casual"],
    dustOff: false,
    image: null,
  },
  {
    id: "9",
    name: "Chelsea Boots",
    category: "Shoes",
    color: "#1C1C1C",
    colorName: "Black",
    fabric: "Leather",
    timesWorn: 18,
    lastWorn: "3 days ago",
    occasions: ["casual", "office"],
    dustOff: false,
    image: null,
  },
  {
    id: "10",
    name: "Oversized Blazer",
    category: "Outerwear",
    color: "#6B5B4E",
    colorName: "Mocha",
    fabric: "Wool Blend",
    timesWorn: 1,
    lastWorn: "1 month ago",
    occasions: ["events"],
    dustOff: true,
    image: null,
  },
];

export const MOCK_OUTFIT_TODAY = {
  headline: "effortless monday",
  subhead: "22° · partly cloudy · meeting at 3pm",
  occasion: "office",
  items: ["Black Cashmere Coat", "White Silk Blouse", "Tailored Wool Trousers", "Leather Oxford Shoes"],
  reasoning: [
    "22° cloudy → coat layer needed",
    "3pm meeting → elevated casual",
    "Last 3 outfits: flowy dresses",
    "Your saved mood: Effortless + Sharp",
  ],
};

export const MOCK_WEEKLY_PLAN = [
  { day: "Mon", short: "M", planned: true, colors: ["#1C1C1C", "#F5EDD6", "#3B2A1A"] },
  { day: "Tue", short: "T", planned: false, colors: [] },
  { day: "Wed", short: "W", planned: true, colors: ["#8B8682", "#C8BCA8"] },
  { day: "Thu", short: "T", planned: false, colors: [] },
  { day: "Fri", short: "F", planned: true, colors: ["#1C1C1C", "#C9A84C"] },
  { day: "Sat", short: "S", planned: false, colors: [] },
  { day: "Sun", short: "S", planned: true, colors: ["#4A3728", "#F5EDD6", "#1C1C1C"] },
];

export const MOCK_TRENDS = [
  {
    id: "1",
    name: "Quiet Luxury",
    tag: "in your closet",
    description: "Understated wealth, impeccable fabric",
  },
  {
    id: "2",
    name: "Office Siren",
    tag: "explore",
    description: "Power dressing with a sharp edge",
  },
  {
    id: "3",
    name: "Coastal Grandmother",
    tag: "explore",
    description: "Linen, comfort, lived-in elegance",
  },
];

export const MOCK_COMMUNITY_POSTS = [
  {
    id: "1",
    handle: "@priya.m",
    lookName: "The Monday Armor",
    aesthetic: "Quiet Luxury",
    hasSimilar: true,
    color: "#2A2218",
  },
  {
    id: "2",
    handle: "@rahul.k",
    lookName: "Friday Energy",
    aesthetic: "Dopamine Dressing",
    hasSimilar: false,
    color: "#1C3040",
  },
  {
    id: "3",
    handle: "@meera.v",
    lookName: "Effortless Sunday",
    aesthetic: "Indie Sleaze",
    hasSimilar: false,
    color: "#251820",
  },
  {
    id: "4",
    handle: "@sofia.d",
    lookName: "Sharp & Clean",
    aesthetic: "Office Siren",
    hasSimilar: true,
    color: "#0D1520",
  },
];

export const MOCK_CALENDAR = {
  planned: {
    "2026-04-09": { colors: ["#1C1C1C", "#F5EDD6", "#3B2A1A"], label: "Office Look" },
    "2026-04-11": { colors: ["#8B8682", "#C8BCA8"], label: "Casual Day" },
    "2026-04-13": { colors: ["#1C1C1C", "#C9A84C"], label: "Dinner Look" },
    "2026-04-15": { colors: ["#4A3728", "#F5EDD6", "#1C1C1C"], label: "Weekend" },
    "2026-04-17": { colors: ["#3B2A1A", "#8B8682"], label: "Event Night" },
  },
};

export const VIBES_STRIP = [
  "Quiet Luxury",
  "Dopamine Dressing",
  "Office Siren",
  "Coastal Grandmother",
  "Indie Sleaze",
  "Dark Academia",
  "Clean Girl",
];

export const INTERVIEW_QUESTIONS = [
  {
    id: 1,
    question: "how do you want to feel\nwhen you walk into a room?",
    type: "tiles",
    options: [
      { label: "Powerful", color: "#1C1C1C" },
      { label: "Effortless", color: "#8B8682" },
      { label: "Playful", color: "#6B3A2A" },
      { label: "Mysterious", color: "#1C1540" },
      { label: "Warm", color: "#8B5E3C" },
      { label: "Sharp", color: "#2A2218" },
    ],
  },
  {
    id: 2,
    question: "what colors live\nin your wardrobe?",
    type: "palette",
    options: [
      { label: "Black", color: "#1C1C1C" },
      { label: "Navy", color: "#1C2A3A" },
      { label: "Ivory", color: "#F5EDD6" },
      { label: "Camel", color: "#C9A84C" },
      { label: "Grey", color: "#8B8682" },
      { label: "Walnut", color: "#4A3728" },
      { label: "Sage", color: "#5A6B5A" },
      { label: "Blush", color: "#C4A09A" },
      { label: "Rust", color: "#8B3A22" },
    ],
  },
  {
    id: 3,
    question: "where does\nyour life happen?",
    type: "icons",
    options: [
      { label: "Office", icon: "briefcase" },
      { label: "Coffee Shops", icon: "coffee" },
      { label: "Campus", icon: "book-open" },
      { label: "Home", icon: "home" },
      { label: "Events", icon: "star" },
      { label: "Outdoors", icon: "wind" },
    ],
  },
  {
    id: 4,
    question: "one brand you\nwish you wore more",
    type: "text",
    brands: ["The Row", "Acne Studios", "Toteme", "Lemaire", "Zara", "Arket", "Cos", "Massimo Dutti", "Aesther Ekme"],
  },
];
